apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jboss-myapp
  labels:
    app: jboss-myapp
spec:
  template:
    metadata:
      labels:
        app: jboss-myapp
    spec:
      containers:
      - name: jboss-myapp
        image: ritaacr.azurecr.io/jboss-myapp
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: mgmt
          containerPort: 9990
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
      imagePullSecrets:
      - name: registrykey
