apiVersion: v1
kind: Service
metadata:
  name: jboss-myapp
  labels:
    app: jboss-myapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: mgmt
    port: 9990
    targetPort: mgmt
  selector:
    app: jboss-myapp
